# Generated by Django 4.2.7 on 2024-04-11 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilisateurs', '__first__'),
        ('sitewebpam', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('password', models.TextField()),
                ('grade', models.CharField(max_length=5)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitewebpam.sitewebpam')),
            ],
        ),
        migrations.CreateModel(
            name='Category_Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment_Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag_Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User_Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Site_Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('Couleur', models.CharField(max_length=50)),
                ('logo', models.ImageField(blank=True, upload_to='static/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(related_name='site_blogs', to='blog.category_blog')),
                ('id_Admin_Blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.admin_blog')),
                ('id_sitepam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitewebpam.sitewebpam')),
                ('tags', models.ManyToManyField(related_name='site_blogs', to='blog.tag_blog')),
            ],
        ),
        migrations.CreateModel(
            name='Post_Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='static/images/')),
                ('content', models.TextField()),
                ('is_featured', models.BooleanField(default=False)),
                ('slug', models.SlugField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.admin_blog')),
                ('categories', models.ManyToManyField(to='blog.category_blog')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.site_blog')),
                ('tags', models.ManyToManyField(to='blog.tag_blog')),
            ],
        ),
        migrations.CreateModel(
            name='Partage_Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.post_blog')),
                ('data_site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sitewebpam.sitewebpam')),
                ('user_Standard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.user_standard')),
                ('user_livreur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.user_livreur')),
                ('user_main', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Note_Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.site_blog')),
                ('user_Standard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.user_standard')),
                ('user_livreur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.user_livreur')),
            ],
        ),
        migrations.CreateModel(
            name='Like_Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.comment_blog')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.post_blog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.user_standard')),
            ],
        ),
        migrations.CreateModel(
            name='Infos_Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone1', models.CharField(max_length=50, null=True)),
                ('phone2', models.CharField(max_length=50, null=True)),
                ('adresse', models.CharField(max_length=255, null=True)),
                ('about', models.CharField(max_length=255, null=True)),
                ('Bio', models.CharField(max_length=255, null=True)),
                ('Infos_supplementaires', models.CharField(max_length=255, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.site_blog')),
            ],
        ),
        migrations.CreateModel(
            name='Follower_Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.site_blog')),
                ('user_Standard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.user_standard')),
                ('user_livreur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.user_livreur')),
                ('user_main', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment_blog',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.user_standard'),
        ),
        migrations.AddField(
            model_name='comment_blog',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post_blog'),
        ),
    ]
