# Generated by Django 4.2.7 on 2024-04-11 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_standard',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='user_standard',
            name='prenom',
        ),
        migrations.AddField(
            model_name='user_standard',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_standard',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_standard',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_standard',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='user_standard',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user_standard',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
