# Generated by Django 4.2.7 on 2024-04-11 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_user_standard_nom_remove_user_standard_prenom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_standard',
            name='nom',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_standard',
            name='prenom',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
