# Generated by Django 4.2.7 on 2024-04-11 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitewebpam', '__first__'),
        ('blog', '0004_alter_user_standard_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_standard',
            name='id_sitepam',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sitewebpam.sitewebpam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_standard',
            name='site',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.site_blog'),
            preserve_default=False,
        ),
    ]
