# Generated by Django 4.2.7 on 2024-04-11 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_user_standard_id_sitepam_user_standard_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_standard',
            name='id_sitepam',
        ),
    ]
