# Generated by Django 4.2.7 on 2024-04-11 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_user_standard_id_sitepam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_standard',
            name='site',
        ),
    ]
