# Generated by Django 4.2.7 on 2024-04-15 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_user_standard_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment_blog',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.comment_blog'),
        ),
    ]
