# Generated by Django 4.2.7 on 2024-04-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_comment_blog_parent_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment_blog',
            name='parent_comment',
        ),
        migrations.AddField(
            model_name='user_standard',
            name='initials',
            field=models.CharField(default=None, max_length=2),
            preserve_default=False,
        ),
    ]
