# Generated by Django 4.2.7 on 2024-04-22 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_comment_blog_parent_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_standard',
            name='site',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.site_blog'),
            preserve_default=False,
        ),
    ]
