# Generated by Django 5.0.3 on 2024-05-10 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_user_standard_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like_blog',
            name='comment',
        ),
    ]
