# Generated by Django 4.2.7 on 2024-05-12 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_like_blog_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.post_blog')),
                ('user_Standard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.user_standard')),
            ],
        ),
    ]
